# Nuxt.js Dockerfile-dev
FROM node:20.15-alpine

ARG WORK_DIR
ARG FRONTEND
ENV WORK_DIR=${WORK_DIR}
ENV FRONTEND=${FRONTEND}

# Install dependencies
WORKDIR ${WORK_DIR}

COPY ./.docker/${FRONTEND}/start-service.sh /usr/local/bin/start-service.sh
RUN chmod +x /usr/local/bin/start-service.sh

# Expose port and start the application
EXPOSE 3000
ENTRYPOINT ["start-service.sh"]