# Nuxt.js Dockerfile2
FROM node:20.15-alpine

# Install dependencies
WORKDIR /var/www/nuxt

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
#RUN npm install

# Copy application files
#COPY . .

# Build the application
#RUN npm run build

# Expose port and start the application
# EXPOSE 3000
# CMD ["npm", "run", "start"]