version: '3'

# --------------------- Enabled services ---------------------
# mariadb - mariadb
# redis - redis
# web - nginx_web
# php - php8.2
#
# --------------------- only live services ------------
# nuxt - node20
#
# --------------------- only development services ------------
# mailhog - mailhog
# node - node20
#
# --------------------- Disabled services ---------------------
# postgres

services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - '${DB_FORWARD_PORT}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_HOST: '${DB_HOST}'
      #      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: '${TZ}'
    volumes:
      - ./.database/mariadb:/var/lib/mysql
      - ./.logs/mariadb:/var/log/mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - docker-network

  postgresql:
    image: postgres:14.4-alpine
    restart: unless-stopped
    ports:
      - '${PG_DB_FORWARD_PORT}:${PG_DB_PORT}'
    environment:
      POSTGRES_DB: '${PG_DB_DATABASE}'
      POSTGRES_USER: '${PG_DB_USERNAME}'
      POSTGRES_PASSWORD: '${PG_DB_PASSWORD}'
    volumes:
      - ./.database/postgresql:/var/lib/postgresql/data
      - ./.logs/postgresql:/var/log/postgresql
    networks:
      - docker-network

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    privileged: true
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/redis/redis.conf
      - ./.database/redis:/data
    ports:
      - '${REDIS_FORWARD_PORT}:${REDIS_PORT}'
    command:
      - redis-server
      - /usr/local/redis/redis.conf
    networks:
      - docker-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s

  php:
    container_name: php8.2
    build:
      context: .
      dockerfile: .docker/php/8.2/Dockerfile
      args:
        # - APP_ENV='production'
        - APP_ENV=${APP_ENV:-local}
        - APP_WORK='/var/www/laravel'
        - TZ=${TZ}
    restart: unless-stopped
    expose:
      - '9000'
    volumes:
      - ./.logs/laravel:/var/log/laravel
      - ./.logs/supervisor:/var/log/supervisor
      - ./laravel:/var/www/laravel
    networks:
      - docker-network
    depends_on:
      - mariadb
      - redis
      - postgresql

  nuxt:
    build:
      context: .
      dockerfile: .docker/nuxt/Dockerfile
#    command: "npm run build && npm run start"
    command: "npm init"
    restart: unless-stopped
    working_dir: /var/www/nuxt
    volumes:
      - ./nuxt:/var/www/nuxt
      - ./.logs/nuxt:/var/log/nuxt
    ports:
      - "${NUXT_FORWARD_PORT}:${NUXT_PORT}"
    networks:
      - docker-network

  #  mailhog:
  #    image: mailhog/mailhog:latest
  #    container_name: mailhog
  #    logging:
  #      driver: 'none'
  #    ports:
  #      - "1025:1025"
  #      - "8025:8025"
  #    networks:
  #      - docker-network

  # node:
  #   container_name: node20
  #   image: node:20-alpine
  #   volumes:
  #     - ./laravel:/var/www/laravel
  #   ports:
  #     - "3000:3000"
  #     # - "4000:4000"
  #   working_dir: /var/www/laravel
  #   depends_on:
  #     - web
  #   entrypoint: [ 'npm' ]
  #   networks:
  #     - docker-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./.certbot/conf:/etc/letsencrypt
      - ./.certbot/www:/var/www/certbot
      - ./.logs/letsencrypt:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - docker-network

  nginx:
    container_name: nginx_web
    build:
      context: .
      dockerfile: .docker/nginx/web/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-www-data}
        - TZ=${TZ}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/web/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/web/ssl:/var/www/ssl
      - ./.logs/nginx:/var/log/nginx
      - ./.certbot/conf:/etc/letsencrypt
      - ./.certbot/www:/var/www/certbot
      - ./laravel:/var/www/laravel
      - ./nuxt:/var/www/nuxt
    depends_on:
      - php
      - mariadb
      - postgresql
      - redis
      - nuxt
    networks:
      - docker-network

networks:
  docker-network: